spring.application.name=demo
google.books.base-url=https://www.googleapis.com/books/v1

# Enable the H2 console
spring.h2.console.enabled=true

# Define the path for the H2 console (default is /h2-console)
spring.h2.console.path=/h2-console

# Configure the data source details
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
